networks:
  servers:

services:

  balancer:
    build: .
    command: go run ./cmd/lb
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build: .
    command: go run ./cmd/server
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8081:8080"

  server2:
    build: .
    command: go run ./cmd/server
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8082:8080"

  server3:
    build: .
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8083:8080"

  db:
    build: .
    command: go run ./cmd/db
    networks:
      - servers
    ports:
      - "8084:8081"
    volumes:
      - dbdata:/app/db-data

volumes:
  dbdata:

